version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      timezone: Europe/London
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - JonPurvis
    labels:
      - dependencies
